# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jayd/Desktop/NUS/UncertaintyModel/project/HandPoseEstimation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jayd/Desktop/NUS/UncertaintyModel/project/HandPoseEstimation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayd/Desktop/NUS/UncertaintyModel/project/HandPoseEstimation/CMakeFiles /home/jayd/Desktop/NUS/UncertaintyModel/project/HandPoseEstimation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jayd/Desktop/NUS/UncertaintyModel/project/HandPoseEstimation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HandPoseEstimation

# Build rule for target.
HandPoseEstimation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HandPoseEstimation
.PHONY : HandPoseEstimation

# fast build rule for target.
HandPoseEstimation/fast:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/build
.PHONY : HandPoseEstimation/fast

LoadData.o: LoadData.cpp.o
.PHONY : LoadData.o

# target to build an object file
LoadData.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/LoadData.cpp.o
.PHONY : LoadData.cpp.o

LoadData.i: LoadData.cpp.i
.PHONY : LoadData.i

# target to preprocess a source file
LoadData.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/LoadData.cpp.i
.PHONY : LoadData.cpp.i

LoadData.s: LoadData.cpp.s
.PHONY : LoadData.s

# target to generate assembly for a file
LoadData.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/LoadData.cpp.s
.PHONY : LoadData.cpp.s

Node.o: Node.cpp.o
.PHONY : Node.o

# target to build an object file
Node.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Node.cpp.o
.PHONY : Node.cpp.o

Node.i: Node.cpp.i
.PHONY : Node.i

# target to preprocess a source file
Node.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Node.cpp.i
.PHONY : Node.cpp.i

Node.s: Node.cpp.s
.PHONY : Node.s

# target to generate assembly for a file
Node.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Node.cpp.s
.PHONY : Node.cpp.s

RandomForest.o: RandomForest.cpp.o
.PHONY : RandomForest.o

# target to build an object file
RandomForest.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/RandomForest.cpp.o
.PHONY : RandomForest.cpp.o

RandomForest.i: RandomForest.cpp.i
.PHONY : RandomForest.i

# target to preprocess a source file
RandomForest.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/RandomForest.cpp.i
.PHONY : RandomForest.cpp.i

RandomForest.s: RandomForest.cpp.s
.PHONY : RandomForest.s

# target to generate assembly for a file
RandomForest.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/RandomForest.cpp.s
.PHONY : RandomForest.cpp.s

Tree.o: Tree.cpp.o
.PHONY : Tree.o

# target to build an object file
Tree.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Tree.cpp.o
.PHONY : Tree.cpp.o

Tree.i: Tree.cpp.i
.PHONY : Tree.i

# target to preprocess a source file
Tree.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Tree.cpp.i
.PHONY : Tree.cpp.i

Tree.s: Tree.cpp.s
.PHONY : Tree.s

# target to generate assembly for a file
Tree.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/Tree.cpp.s
.PHONY : Tree.cpp.s

calSim.o: calSim.cpp.o
.PHONY : calSim.o

# target to build an object file
calSim.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/calSim.cpp.o
.PHONY : calSim.cpp.o

calSim.i: calSim.cpp.i
.PHONY : calSim.i

# target to preprocess a source file
calSim.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/calSim.cpp.i
.PHONY : calSim.cpp.i

calSim.s: calSim.cpp.s
.PHONY : calSim.s

# target to generate assembly for a file
calSim.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/calSim.cpp.s
.PHONY : calSim.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/HandPoseEstimation.dir/build.make CMakeFiles/HandPoseEstimation.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... HandPoseEstimation"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... LoadData.o"
	@echo "... LoadData.i"
	@echo "... LoadData.s"
	@echo "... Node.o"
	@echo "... Node.i"
	@echo "... Node.s"
	@echo "... RandomForest.o"
	@echo "... RandomForest.i"
	@echo "... RandomForest.s"
	@echo "... Tree.o"
	@echo "... Tree.i"
	@echo "... Tree.s"
	@echo "... calSim.o"
	@echo "... calSim.i"
	@echo "... calSim.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

